--------------------------------------------------------
--  File created - Thursday-March-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONSTRUCTORS
--------------------------------------------------------

  CREATE TABLE "ABIOWE"."CONSTRUCTORS" 
   (	"CONSTRUCTORID" NUMBER(38,0), 
	"CONSTRUCTORREF" VARCHAR2(26 BYTE), 
	"NAME" VARCHAR2(26 BYTE), 
	"NATIONALITY" VARCHAR2(26 BYTE), 
	"URL" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ABIOWE.CONSTRUCTORS
SET DEFINE OFF;
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (1,'mclaren','McLaren','British','http://en.wikipedia.org/wiki/McLaren');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (2,'bmw_sauber','BMW Sauber','German','http://en.wikipedia.org/wiki/BMW_Sauber');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (3,'williams','Williams','British','http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (4,'renault','Renault','French','http://en.wikipedia.org/wiki/Renault_F1');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (5,'toro_rosso','Toro Rosso','Italian','http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (6,'ferrari','Ferrari','Italian','http://en.wikipedia.org/wiki/Scuderia_Ferrari');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (7,'toyota','Toyota','Japanese','http://en.wikipedia.org/wiki/Toyota_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (8,'super_aguri','Super Aguri','Japanese','http://en.wikipedia.org/wiki/Super_Aguri_F1');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (9,'red_bull','Red Bull','Austrian','http://en.wikipedia.org/wiki/Red_Bull_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (10,'force_india','Force India','Indian','http://en.wikipedia.org/wiki/Force_India');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (11,'honda','Honda','Japanese','http://en.wikipedia.org/wiki/Honda_Racing_F1');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (12,'spyker','Spyker','Dutch','http://en.wikipedia.org/wiki/Spyker_F1');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (13,'mf1','MF1','Russian','http://en.wikipedia.org/wiki/Midland_F1_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (14,'spyker_mf1','Spyker MF1','Dutch','http://en.wikipedia.org/wiki/Midland_F1_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (15,'sauber','Sauber','Swiss','http://en.wikipedia.org/wiki/Sauber');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (16,'bar','BAR','British','http://en.wikipedia.org/wiki/British_American_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (17,'jordan','Jordan','Irish','http://en.wikipedia.org/wiki/Jordan_Grand_Prix');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (18,'minardi','Minardi','Italian','http://en.wikipedia.org/wiki/Minardi');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (19,'jaguar','Jaguar','British','http://en.wikipedia.org/wiki/Jaguar_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (20,'prost','Prost','French','http://en.wikipedia.org/wiki/Prost_Grand_Prix');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (21,'arrows','Arrows','British','http://en.wikipedia.org/wiki/Arrows_Grand_Prix_International');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (22,'benetton','Benetton','Italian','http://en.wikipedia.org/wiki/Benetton_Formula');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (23,'brawn','Brawn','British','http://en.wikipedia.org/wiki/Brawn_GP');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (24,'stewart','Stewart','British','http://en.wikipedia.org/wiki/Stewart_Grand_Prix');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (25,'tyrrell','Tyrrell','British','http://en.wikipedia.org/wiki/Tyrrell_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (26,'lola','Lola','British','http://en.wikipedia.org/wiki/MasterCard_Lola');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (27,'ligier','Ligier','French','http://en.wikipedia.org/wiki/Ligier');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (28,'forti','Forti','Italian','http://en.wikipedia.org/wiki/Forti');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (29,'footwork','Footwork','British','http://en.wikipedia.org/wiki/Footwork_Arrows');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (30,'pacific','Pacific','British','http://en.wikipedia.org/wiki/Pacific_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (31,'simtek','Simtek','British','http://en.wikipedia.org/wiki/Simtek');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (32,'team_lotus','Team Lotus','British','http://en.wikipedia.org/wiki/Team_Lotus');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (33,'larrousse','Larrousse','French','http://en.wikipedia.org/wiki/Larrousse');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (34,'brabham','Brabham','British','http://en.wikipedia.org/wiki/Brabham');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (35,'dallara','Dallara','Italian','http://en.wikipedia.org/wiki/Dallara');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (36,'fondmetal','Fondmetal','Italian','http://en.wikipedia.org/wiki/Fondmetal');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (37,'march','March','British','http://en.wikipedia.org/wiki/March_Engineering');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (38,'moda','Andrea Moda','Italian','http://en.wikipedia.org/wiki/Andrea_Moda_Formula');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (39,'ags','AGS','French','http://en.wikipedia.org/wiki/Automobiles_Gonfaronnaises_Sportives');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (40,'lambo','Lambo','Italian','http://en.wikipedia.org/wiki/Modena_(racing_team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (41,'leyton','Leyton House','British','http://en.wikipedia.org/wiki/Leyton_House');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (42,'coloni','Coloni','Italian','http://en.wikipedia.org/wiki/Enzo_Coloni_Racing_Car_Systems');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (44,'eurobrun','Euro Brun','Italian','http://en.wikipedia.org/wiki/Euro_Brun');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (45,'osella','Osella','Italian','http://en.wikipedia.org/wiki/Osella');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (46,'onyx','Onyx','British','http://en.wikipedia.org/wiki/Onyx_(racing_team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (47,'life','Life','Italian','http://en.wikipedia.org/wiki/Life_(Racing_Team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (48,'rial','Rial','German','http://en.wikipedia.org/wiki/Rial_%28racing_team%29');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (49,'zakspeed','Zakspeed','German','http://en.wikipedia.org/wiki/Zakspeed');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (50,'ram','RAM','British','http://en.wikipedia.org/wiki/RAM_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (51,'alfa','Alfa Romeo','Italian','http://en.wikipedia.org/wiki/Alfa_Romeo_(Formula_One)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (52,'spirit','Spirit','British','http://en.wikipedia.org/wiki/Spirit_(racing_team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (53,'toleman','Toleman','British','http://en.wikipedia.org/wiki/Toleman');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (54,'ats','ATS','Italian','http://en.wikipedia.org/wiki/ATS_(wheels)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (55,'theodore','Theodore','Hong Kong','http://en.wikipedia.org/wiki/Theodore_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (56,'fittipaldi','Fittipaldi','Brazilian','http://en.wikipedia.org/wiki/Fittipaldi_%28constructor%29');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (57,'ensign','Ensign','British','http://en.wikipedia.org/wiki/Ensign_%28racing_team%29');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (58,'shadow','Shadow','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (59,'wolf','Wolf','Canadian','http://en.wikipedia.org/wiki/Walter_Wolf_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (60,'merzario','Merzario','Italian','http://en.wikipedia.org/wiki/Merzario');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (61,'kauhsen','Kauhsen','German','http://en.wikipedia.org/wiki/Kauhsen');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (62,'rebaque','Rebaque','Mexican','http://en.wikipedia.org/wiki/Rebaque');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (63,'surtees','Surtees','British','http://en.wikipedia.org/wiki/Surtees');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (64,'hesketh','Hesketh','British','http://en.wikipedia.org/wiki/Hesketh_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (65,'martini','Martini','French','http://en.wikipedia.org/wiki/Martini_(cars)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (66,'brm','BRM','British','http://en.wikipedia.org/wiki/BRM');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (67,'penske','Penske','American','http://en.wikipedia.org/wiki/Penske_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (68,'lec','LEC','British','http://en.wikipedia.org/wiki/LEC_(Formula_One)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (69,'mcguire','McGuire','Australian','http://en.wikipedia.org/wiki/McGuire_(Formula_One)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (70,'boro','Boro','Dutch','http://en.wikipedia.org/wiki/Boro_(Formula_One)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (71,'apollon','Apollon','Swiss','http://en.wikipedia.org/wiki/Apollon_(Formula_One)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (72,'kojima','Kojima','Japanese','http://en.wikipedia.org/wiki/Kojima_Engineering');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (73,'parnelli','Parnelli','American','http://en.wikipedia.org/wiki/Parnelli');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (74,'maki','Maki','Japanese','http://en.wikipedia.org/wiki/Maki_(cars)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (75,'hill','Embassy Hill','British','http://en.wikipedia.org/wiki/Hill_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (76,'lyncar','Lyncar','British','http://en.wikipedia.org/wiki/Lyncar');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (77,'trojan','Trojan','British','http://en.wikipedia.org/wiki/Trojan_(Racing_team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (78,'amon','Amon','New Zealand','http://en.wikipedia.org/wiki/Amon_(Formula_One_team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (79,'token','Token','British','http://en.wikipedia.org/wiki/Token_(Racing_team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (80,'iso_marlboro','Iso Marlboro','British','http://en.wikipedia.org/wiki/Iso_Marlboro');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (81,'tecno','Tecno','Italian','http://en.wikipedia.org/wiki/Tecno');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (82,'matra','Matra','French','http://en.wikipedia.org/wiki/Matra');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (83,'politoys','Politoys','British','http://en.wikipedia.org/wiki/Frank_Williams_Racing_Cars');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (84,'connew','Connew','British','http://en.wikipedia.org/wiki/Connew');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (85,'bellasi','Bellasi','Swiss','http://en.wikipedia.org/wiki/Bellasi');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (86,'tomaso','De Tomaso','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (87,'cooper','Cooper','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (88,'eagle','Eagle','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (89,'lds','LDS','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (90,'protos','Protos','British','http://en.wikipedia.org/wiki/Protos_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (91,'shannon','Shannon','British','http://en.wikipedia.org/wiki/Shannon_(Formula_One)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (92,'scirocco','Scirocco','British','http://en.wikipedia.org/wiki/Scirocco-Powell');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (93,'re','RE','Rhodesian','http://en.wikipedia.org/wiki/RE_%28automobile%29');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (94,'brp','BRP','British','http://en.wikipedia.org/wiki/British_Racing_Partnership');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (95,'porsche','Porsche','German','http://en.wikipedia.org/wiki/Porsche_in_Formula_One');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (96,'derrington','Derrington','British','http://en.wikipedia.org/wiki/Derrington-Francis');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (97,'gilby','Gilby','British','http://en.wikipedia.org/wiki/Gilby');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (98,'stebro','Stebro','Canadian','http://en.wikipedia.org/wiki/Stebro');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (99,'emeryson','Emeryson','British','http://en.wikipedia.org/wiki/Emeryson');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (100,'enb','ENB','Belgium','http://en.wikipedia.org/wiki/Ecurie_Nationale_Belge');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (101,'jbw','JBW','British','http://en.wikipedia.org/wiki/JBW');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (102,'ferguson','Ferguson','British','http://en.wikipedia.org/wiki/Ferguson_Research_Ltd.');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (103,'mbm','MBM','Swiss','http://en.wikipedia.org/wiki/Monteverdi_Basel_Motors');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (104,'behra-porsche','Behra-Porsche','Italian','http://en.wikipedia.org/wiki/Behra-Porsche');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (105,'maserati','Maserati','Italian','http://en.wikipedia.org/wiki/Maserati');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (106,'scarab','Scarab','American','http://en.wikipedia.org/wiki/Scarab_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (107,'watson','Watson','American','http://en.wikipedia.org/wiki/A.J._Watson');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (108,'epperly','Epperly','American','http://en.wikipedia.org/wiki/Epperly');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (109,'phillips','Phillips','American','http://en.wikipedia.org/wiki/Phillips_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (110,'lesovsky','Lesovsky','American','http://en.wikipedia.org/wiki/Lesovsky');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (111,'trevis','Trevis','American','http://en.wikipedia.org/wiki/Trevis');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (112,'meskowski','Meskowski','American','http://en.wikipedia.org/wiki/Meskowski');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (113,'kurtis_kraft','Kurtis Kraft','American','http://en.wikipedia.org/wiki/Kurtis_Kraft');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (114,'kuzma','Kuzma','American','http://en.wikipedia.org/wiki/Kuzma_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (115,'vhristensen','Christensen','American','http://en.wikipedia.org/wiki/Christensen_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (116,'ewing','Ewing','American','http://en.wikipedia.org/wiki/Ewing_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (117,'aston_martin','Aston Martin','British','http://en.wikipedia.org/wiki/Aston_Martin');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (118,'vanwall','Vanwall','British','http://en.wikipedia.org/wiki/Vanwall');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (119,'moore','Moore','American','http://en.wikipedia.org/wiki/Moore_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (120,'dunn','Dunn','American','http://en.wikipedia.org/wiki/Dunn_Engineering');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (121,'elder','Elder','American','http://en.wikipedia.org/wiki/Elder_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (122,'sutton','Sutton','American','http://en.wikipedia.org/wiki/Sutton_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (123,'fry','Fry','British','http://en.wikipedia.org/wiki/Fry_(racing_team)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (124,'tec-mec','Tec-Mec','Italian','http://en.wikipedia.org/wiki/Tec-Mec');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (125,'connaught','Connaught','British','http://en.wikipedia.org/wiki/Connaught_Engineering');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (126,'alta','Alta','British','http://en.wikipedia.org/wiki/Alta_auto_racing_team');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (127,'osca','OSCA','Italian','http://en.wikipedia.org/wiki/Officine_Specializate_Costruzione_Automobili');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (128,'gordini','Gordini','French','http://en.wikipedia.org/wiki/Gordini');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (129,'stevens','Stevens','American','http://en.wikipedia.org/wiki/Stevens_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (130,'bugatti','Bugatti','French','http://en.wikipedia.org/wiki/Bugatti');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (131,'mercedes','Mercedes','German','http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (132,'lancia','Lancia','Italian','http://en.wikipedia.org/wiki/Lancia_in_Formula_One');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (133,'hwm','HWM','British','http://en.wikipedia.org/wiki/Hersham_and_Walton_Motors');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (134,'schroeder','Schroeder','American','http://en.wikipedia.org/wiki/Schroeder_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (135,'pawl','Pawl','American','http://en.wikipedia.org/wiki/Pawl_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (136,'pankratz','Pankratz','American','http://en.wikipedia.org/wiki/Pankratz');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (137,'arzani-volpini','Arzani-Volpini','Italian','http://en.wikipedia.org/wiki/Arzani-Volpini');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (138,'nichels','Nichels','American','http://en.wikipedia.org/wiki/Nichels');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (139,'bromme','Bromme','American','http://en.wikipedia.org/wiki/Bromme');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (140,'klenk','Klenk','German','http://en.wikipedia.org/wiki/Klenk');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (141,'simca','Simca','French','http://en.wikipedia.org/wiki/Simca');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (142,'turner','Turner','American','http://en.wikipedia.org/wiki/Turner_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (143,'del_roy','Del Roy','American','http://en.wikipedia.org/wiki/Del_Roy');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (144,'veritas','Veritas','German','http://en.wikipedia.org/wiki/Veritas_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (145,'bmw','BMW','German','http://en.wikipedia.org/wiki/BMW');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (146,'emw','EMW','East German','http://en.wikipedia.org/wiki/Eisenacher_Motorenwerk');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (147,'afm','AFM','German','http://en.wikipedia.org/wiki/Alex_von_Falkenhausen_Motorenbau');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (148,'frazer_nash','Frazer Nash','British','http://en.wikipedia.org/wiki/Frazer_Nash');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (149,'sherman','Sherman','American','http://en.wikipedia.org/wiki/Sherman_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (150,'deidt','Deidt','American','http://en.wikipedia.org/wiki/Deidt');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (151,'era','ERA','British','http://en.wikipedia.org/wiki/English_Racing_Automobiles');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (152,'butterworth','Aston Butterworth','British','http://en.wikipedia.org/wiki/Aston_Butterworth');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (153,'cisitalia','Cisitalia','Italian','http://en.wikipedia.org/wiki/Cisitalia');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (154,'lago','Talbot-Lago','French','http://en.wikipedia.org/wiki/Talbot-Lago');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (155,'hall','Hall','American','http://en.wikipedia.org/wiki/Hall_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (156,'marchese','Marchese','American','http://en.wikipedia.org/wiki/Marchese_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (157,'langley','Langley','American','http://en.wikipedia.org/wiki/Langley_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (158,'rae','Rae','American','http://en.wikipedia.org/wiki/Rae_(motorsport)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (159,'olson','Olson','American','http://en.wikipedia.org/wiki/Olson_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (160,'wetteroth','Wetteroth','American','http://en.wikipedia.org/wiki/Wetteroth');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (161,'adams','Adams','American','http://en.wikipedia.org/wiki/Adams_(constructor)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (162,'snowberger','Snowberger','American','http://en.wikipedia.org/wiki/Snowberger');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (163,'milano','Milano','Italian','http://en.wikipedia.org/wiki/Scuderia_Milano');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (164,'hrt','HRT','Spanish','http://en.wikipedia.org/wiki/Hispania_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (167,'cooper-maserati','Cooper-Maserati','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (166,'virgin','Virgin','British','http://en.wikipedia.org/wiki/Virgin_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (168,'cooper-osca','Cooper-OSCA','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (169,'cooper-borgward','Cooper-Borgward','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (170,'cooper-climax','Cooper-Climax','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (171,'cooper-castellotti','Cooper-Castellotti','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (172,'lotus-climax','Lotus-Climax','British','http://en.wikipedia.org/wiki/Team_Lotus');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (173,'lotus-maserati','Lotus-Maserati','British','http://en.wikipedia.org/wiki/Team_Lotus');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (174,'de_tomaso-osca','De Tomaso-Osca','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (175,'de_tomaso-alfa_romeo','De Tomaso-Alfa Romeo','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (176,'lotus-brm','Lotus-BRM','British','http://en.wikipedia.org/wiki/Team_Lotus');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (177,'lotus-borgward','Lotus-Borgward','British','http://en.wikipedia.org/wiki/Team_Lotus');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (178,'cooper-alfa_romeo','Cooper-Alfa Romeo','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (179,'de_tomaso-ferrari','De Tomaso-Ferrari','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (180,'lotus-ford','Lotus-Ford','British','http://en.wikipedia.org/wiki/Team_Lotus');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (181,'brabham-brm','Brabham-BRM','British','http://en.wikipedia.org/wiki/Brabham');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (182,'brabham-ford','Brabham-Ford','British','http://en.wikipedia.org/wiki/Brabham');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (183,'brabham-climax','Brabham-Climax','British','http://en.wikipedia.org/wiki/Brabham');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (184,'lds-climax','LDS-Climax','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (185,'lds-alfa_romeo','LDS-Alfa Romeo','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (186,'cooper-ford','Cooper-Ford','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (187,'mclaren-ford','McLaren-Ford','British','http://en.wikipedia.org/wiki/Team_McLaren');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (188,'mclaren-seren','McLaren-Serenissima','British','http://en.wikipedia.org/wiki/Team_McLaren');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (189,'eagle-climax','Eagle-Climax','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (190,'eagle-weslake','Eagle-Weslake','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (191,'brabham-repco','Brabham-Repco','British','http://en.wikipedia.org/wiki/Brabham');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (192,'cooper-ferrari','Cooper-Ferrari','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (193,'cooper-ats','Cooper-ATS','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (194,'mclaren-brm','McLaren-BRM','British','http://en.wikipedia.org/wiki/McLaren_(racing)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (195,'cooper-brm','Cooper-BRM','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (196,'matra-ford','Matra-Ford','French','http://en.wikipedia.org/wiki/Matra');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (197,'brm-ford','BRM-Ford','British','http://en.wikipedia.org/wiki/BRM');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (198,'mclaren-alfa_romeo','McLaren-Alfa Romeo','British','http://en.wikipedia.org/wiki/McLaren_(racing)');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (199,'march-alfa_romeo','March-Alfa Romeo','British','http://en.wikipedia.org/wiki/March_Engineering');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (200,'march-ford','March-Ford','British','http://en.wikipedia.org/wiki/March_Engineering');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (201,'lotus-pw','Lotus-Pratt &amp; Whitney','British','http://en.wikipedia.org/wiki/Team_Lotus');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (202,'shadow-ford','Shadow-Ford','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (203,'shadow-matra','Shadow-Matra','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (204,'brabham-alfa_romeo','Brabham-Alfa Romeo','British','http://en.wikipedia.org/wiki/Brabham');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (205,'lotus_racing','Lotus','Malaysian','http://en.wikipedia.org/wiki/Lotus_Racing');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (206,'marussia','Marussia','Russian','http://en.wikipedia.org/wiki/Marussia_F1');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (207,'caterham','Caterham','Malaysian','http://en.wikipedia.org/wiki/Caterham_F1');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (208,'lotus_f1','Lotus F1','British','http://en.wikipedia.org/wiki/Lotus_F1');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (209,'manor','Manor Marussia','British','http://en.wikipedia.org/wiki/Manor_Motorsport');
Insert into ABIOWE.CONSTRUCTORS (CONSTRUCTORID,CONSTRUCTORREF,NAME,NATIONALITY,URL) values (210,'haas','Haas F1 Team','American','http://en.wikipedia.org/wiki/Haas_F1_Team');
